### ISSUE TITLE
Add overrideLogDirectory to Adapter options

### ISSUE THREAD

**Issue by ablesea** [abaga129/sveltekit-adapter-iis#15]
This would allow you to avoid configuring a log directory every time. I'm happy to work on this one.

Add to iisnode config like this:
```
<iisnode ... logDirectory="C:\My App\logs"/>
```

Steps
- [ ] Add overrideLogDirectory to AdapterOptions declaration file
- [ ] Add to createWebConfig function
- [ ] Update README with override docs

**Comment by ablesea** [comment]
For now if anyone else is wanting to do the same thing you can inject it by doing something like this:
```xml
adapter: IISAdapter({
   overrideNodeExePath: "C:\\Program Files\\nodejs\\node.exe\" logDirectory=\"C:\\My App\\logs",
}),
```

**Comment by abaga129** [comment]
Hey sorry I just saw this.  Yeah I think this would be a worthwhile change and shouldn't be too difficult to add.  A PR would be welcome!

**Comment by ablesea** [comment]
I will open one this afternoon

**Comment by ablesea** [comment]
I think I will go ahead and define an interface for all IISnode properties so that anything else will already be there as well

**Comment by abaga129** [comment]
Sounds like a good idea to me.  I'm sure there are many things from IIS-node that havent been thought of.  My initial implementation just kind of scratched the service of what was needed to get an app in production for my specific use-case.  I'm glad to see this being used and extended by others!

**Comment by ieedan** [comment]
The way I want to do it will be a breaking change. It would add a iisNodeOptions property to adapter options moving overrideNodeExe to the issNodeOptions object

**Comment by KraXen72** [comment]
you can introduce the new iisNodeOptions object while keeping the old one and adding a `@deprecated` jsdoc guiding developers to use the new object. it would be a good idea to only introduce breaking changes on major versions, as per semver. what do you think about this, @abaga129 ?

**Comment by ieedan** [comment]
> you can introduce the new iisNodeOptions object while keeping the old one and adding a `@deprecated` jsdoc guiding developers to use the new object. it would be a good idea to only introduce breaking changes on major versions, as per semver. what do you think about this, @abaga129 ?

Like this?
```js
/** @deprecated use iisNodeOptions instead */
overrideNodeExePath?: string
```

**Comment by abaga129** [comment]
@KraXen72 good thinking.  It's best not to introduce breaking changes if it can be avoided for now.
