### ISSUE TITLE
First build with adapter will fail due to missing .svelte-kit/adapter-iis directory

### ISSUE THREAD

**Issue by abaga129** [abaga129/sveltekit-adapter-iis#3]
`.svelte-kit/adapter-iis` needs to either be created before cleaning up the output directory or skipped if it doesnt exist.

**Comment by KraXen72** [comment]
it creates it for me i think? but no harm in a mkdirSync

**Comment by KraXen72** [comment]
also, the readme should probably be updated to first recommend installing from npm, and not my fork xdd

**Comment by abaga129** [comment]
Good point.  I updated the README and I fixed this issue.  Maybe its something different depending on environment?  I know that if I deleted the .svelte-kit directory, it would  cause the adapter to fail until I manually created the directory.
